server:
  port: 8080
spring:
  datasource:
    driver-class-name: ${leading.datasource.driver-class-name}
    type: ${leading.datasource.type}
    url: ${leading.datasource.url}
    username: ${leading.datasource.username}
    password: ${leading.datasource.password}
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    redis:
      host: ${leading.data.redis.host}
      port: ${leading.data.redis.port}
      database: ${leading.data.redis.database}
  application:
    name: AI_Study_Rest_Hub
  profiles:
    active: dev
  ai:
    dashscope:
      agent:
        options:
          app-id: ${leading.ai.dashscope.agent.api-id}
      api-key: ${leading.ai.dashscope.api-key}
springdoc:
  default-flat-param-object: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
minio:
  endpoint: ${minio.endpoint}
  access-key: ${minio.access-key}
  secret-key: ${minio.secret-key}
  bucket-name: ${minio.bucket-name}
leading:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: your-very-long-and-secure-secret-key-32-chars-minimum
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token